import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Button } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>HackItForward</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button p={4} m={4}>Sign In</Button>
    </Box>
  )
}

export default Home
